### ISSUE TITLE
Broken Links in to https://about.freecodecamp.org/*

### ISSUE THREAD

**Issue by honmanyau** [freeCodeCamp/about#13]
## Summary

Several links on the live [About](https://about.freecodecamp.org/) return 404 as they are relative links that redirect to page on the about.freecodecamp.org subdomain instead of absolute links that redirect back to www.freecodecamp.org.

### **Helpful Links** Section

The following links return 404:

* [Our privacy policy](https://about.freecodecamp.org/privacy)([correct link](https://www.freecodecamp.org/privacy))
* [Our code of conduct](https://about.freecodecamp.org/code-of-conduct)([correct link](https://www.freecodecamp.org/code-of-conduct))
* [Our academic honesty policy](https://about.freecodecamp.org/academic-honesty)([correct link](https://www.freecodecamp.org/academic-honesty))
* [Our terms of service](https://about.freecodecamp.org/terms)([correct link](https://www.freecodecamp.org/terms))

### freeCodeCamp Logo Redirection

Clicking on the logo returns 404:

* [Next Challenge](https://about.freecodecamp.org/challenges/next-challenge)([correct link](https://www.freecodecamp.org/challenges/next-challenge))

In addition, I think the logo should either redirect users back to https://www.freecodecamp.org or the https://forum.freecodecamp.org (the latter is how I got to the About page in the first place).

**Comment by QuincyLarson** [comment]
@honmanyau Awesome - thank you for noticing this and opening this issue! I'll fix this.
